### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MESSAGE_FILE_TYPE_EVENT'

### ISSUE THREAD

**Issue by SkiTheSlicer** [libyal/winevt-kb#13] opened 2017-03-10 05:34 UTC
After installing dependencies, cloning and installing master, running `export.py --db winevt-rc_new.db --string_format pep3101 dir_from_extract/` results in:
`AttributeError: 'module' object has no attribute 'MESSAGE_FILE_TYPE_EVENT'`

Fixed with:
```
unzip /usr/local/lib/python2.7/dist-packages/winevtrc-20160418-py2.7.egg EGG-INFO/scripts/export.py
sed -i 's|database.MESSAGE_FILE_TYPE_EVENT|database.definitions.MESSAGE_FILE_TYPE_EVENT|' EGG-INFO/scripts/export.py
sudo zip -u /usr/local/lib/python2.7/dist-packages/winevtrc-20160418-py2.7.egg EGG-INFO/scripts/export.py
```

**Comment by joachimmetz** [comment] 2017-03-10 06:23
Thx for the report. I'll have a look if I reproduce this when time permits. Currently I'm working on improving test  coverage, for better plaso integration eventually.

**Comment by joachimmetz** [comment] 2021-12-31 07:46
Looks like the issue has been addressed in the meantime

**Closed as completed by joachimmetz** 2021-12-31 07:46 UTC
